on:
  pull_request:
    types: [ready_for_review]
jobs:
  ready-for-review-labeling-job:
    runs-on: ubuntu-latest
    name: A job to label a pull request as ready-for-review
    permissions:
      pull-requests: write
    steps:
      - name: Label as ready for review
        id: ready-for-review
        uses: nikasulo/pr-labeler@v1
        with:
          action-type: APPROVED
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-author: ${{ github.event.pull_request.user.login }}
          pr-number: ${{ github.event.pull_request.number }}
